#!/bin/bash

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey

# export XDG_SESSION_TYPE=x11
# export GDK_BACKEND=x11
# export DISPLAY=:0.0 
export XKL_XMODMAP_DISABLE=1
export XDG_CURRENT_DESKTOP="GNOME-Flashback:GNOME"
export XDG_MENU_PREFIX="gnome-flashback-"
# fix gnome-terminal
#   reference: https://askubuntu.com/questions/608330/problem-with-gnome-terminal-on-gnome-3-12-2
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

gnome-session --session=gnome-flashback-metacity --disable-acceleration-check &